version: 2.1

name: Terraform CI/CD

jobs:
  terraform_plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Change wapper permission
          command: chmod +x terraform_wrapper.sh
      - run:
          name: Initialize Terraform
          command: ./terraform_wrapper.sh -a init -d parameters.dir
      - run:
          name: Terraform Apply
          command: ./terraform_wrapper.sh -a plan -d parameters.dir 


  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
    parameters:
      dir:
        type: string
    steps:
      - checkout
      - run:
          name: Change wapper permission
          command: chmod +x terraform_wrapper.sh
      - run:
          name: Initialize Terraform
          command: ./terraform_wrapper.sh -a init -d parameters.dir
      - run:
          name: Terraform Apply
          command: ./terraform_wrapper.sh -a apply -d parameters.dir 

  terraform_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure Terraform
        run: |
          terraform init \
            -backend-config="bucket=my-terraform-state" \
            -backend-config="region=us-west-2" \
            -backend-config="dynamodb_table=my-terraform-state-lock"
      - name: Validate Terraform
        run: terraform validate
      - name: Apply Terraform
        run: terraform apply -auto-approve


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - terraform_plan
      - terraform_apply:
          requires:
            - terraform_plan
# jobs:
#   build:
#     docker:
#       - image: cimg/base:2023.06
#     steps:
#       - checkout
#       - run:
#           name: Run migrations
#           command: sql/docker-entrypoint.sh sql
#           # Environment variable for a single command shell
#           environment:
#             DATABASE_URL: postgres://conductor:@localhost:5432/conductor_test
