version: 2.1

name: Terraform CI/CD

jobs:
  terraform_plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan

  terraform_apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - terraform_plan
      - terraform_apply:
          requires:
            - terraform_plan
# jobs:
#   build:
#     docker:
#       - image: cimg/base:2023.06
#     steps:
#       - checkout
#       - run:
#           name: Run migrations
#           command: sql/docker-entrypoint.sh sql
#           # Environment variable for a single command shell
#           environment:
#             DATABASE_URL: postgres://conductor:@localhost:5432/conductor_test
